# Generated by Django 4.1.1 on 2022-09-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("capacity", models.IntegerField(default=1)),
                ("projector", models.BooleanField(default=False)),
                ("floor", models.IntegerField(default=1)),
                ("number", models.IntegerField(default=1001)),
                ("note", models.TextField(blank=True)),
            ],
        ),
    ]
