# Generated by Django 4.1.1 on 2022-09-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="duration",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
