# Generated by Django 4.1.1 on 2022-09-20 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
        ("meetings", "0002_alter_meeting_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rooms.room"
            ),
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
